project:
  type: website

website:
  navbar:
    background: dark
    search: true
    left:
      - text: "População"
        href: index.qmd
      - text: "Ocupação"
        href: ocupacao.qmd
      - text: "Decomposição da Ocupação"
        href: decomposicao.qmd
    tools:
    - icon: github
      menu:
        - text: Source Code
          href:  https://github.com/felipequentino/app-live-data

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



